tobat_homepage:
    path:     /
    defaults: { _controller: TobatBundle:Default:index }

index_client:
    path:     /clients
    defaults: { _controller: TobatBundle:Client:index }

ajout_commentaire:
    path:     /client/{id}/ajout/commentaire
    defaults: { _controller: TobatBundle:Client:ajoutCommentaire }

ajout_bateau_client:
    path:     /client/{id_client}/ajout/bateau/{id_bateau}
    defaults: { _controller: TobatBundle:Client:ajoutBateauClient }

supression_bateau_client:
    path:     /client/{id_client}/supression/bateau/{id_bateau}
    defaults: { _controller: TobatBundle:Client:supressionBateauClient }

afficher_client:
    path:     /client/{id_client}
    defaults: {_controller:TobatBundle:Client:afficherClient}

update_client:
    path:     /client/{id_client}/update
    defaults: {_controller:TobatBundle:Client:updateClient}

delete_client:
    path:     /client/{id_client}/delete
    defaults: {_controller:TobatBundle:Client:deleteClient}

index_bateau:
    path:     /bateaux
    defaults: {_controller:TobatBundle:Bateau:index}
