tobat_homepage:
    path:     /
    defaults: { _controller: TobatBundle:Default:index }

index_client:
    path:     /clients
    defaults: { _controller: TobatBundle:Client:index }

ajout_commentaire:
    path:     /client/{id}/ajout/commentaire
    defaults: { _controller: TobatBundle:Client:ajoutCommentaire }

ajout_bateau_client:
    path:     /client/{id_client}/ajout/bateau/{id_bateau}
    defaults: { _controller: TobatBundle:Client:ajoutBateauClient }
